config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :posts, only: :index
  resources :reports, only: :index do
    collection do
      get 'top-user-posts'
      get 'top-user-likes'
      get 'top-posts'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/concerns/followable.rb
module Followable
  extend ActiveSupport::Concern

  included do
    has_many :followed_relations, class_name: 'Follow',
                                foreign_key: 'follower_id',
                                dependent: :destroy
    has_many :follower_relations, class_name: 'Follow',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy
    has_many :following, through: :followed_relations, source: :followed
    has_many :followers, through: :follower_relations, source: :follower
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :media
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  include Followable
  has_many :posts

  def like(post)
    post.likes.create(user: self)
  end

  def publish(description, *media)
    post = posts.create(description: description)
    media.each do |medium|
      post.media << medium
    end
    post
  end

  def comment(body, post)
    post.comments.create(user: self, body: body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user, :media, likes: :user, comments: :user).all
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def top_user_posts
    @users = OrderUserQuery.new(:posts).top_posts
  end

  def top_user_likes
    @users = OrderUserQuery.new({ posts: :likes }).top_likes
  end

  def top_posts
    @posts = OrderPostQuery.new.top_likes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
    @user_decorator = UserDecorator.new(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "The user was deleted"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :private_email, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def fullname(user)
    "#{user.first_name} #{user.last_name}"
  end

  def users_list(list)
    content_tag :ul do
      list.collect do |user|
        concat content_tag :li, link_to(fullname(user), user)
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instacopy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Users", users_path %>
    <%= link_to "Posts", posts_path %>
    <%= link_to "Reports", reports_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Lists of Posts</h1>
<section>
  <% @posts.each do |post| %>
    <article>
      <h3><%= post.description %></h3>
      Author:
      <%= link_to post.user.first_name + ' ' + post.user.last_name, post.user %>
      <br />

      Media:
      <% if post.media.any? %>
        <ul>
          <% post.media.each do |medium| %>
            <li><%= medium.name %></li>
          <% end %>
        </ul>
      <% else %>
        No media
      <% end %>
      <br />

      Likes:
      <% if post.likes.any? %>
        <ul>
          <% post.likes.each do |like| %>
            <li><%= link_to like.user.first_name + ' ' + like.user.last_name, like.user %></li>
          <% end %>
        </ul>
      <% else %>
        No likes
      <% end %>
      <br />

      Comments:
      <% if post.comments.any? %>
        <ul>
          <% post.comments.each do |comment| %>
            <li><%= comment.body %> - <%=  link_to comment.user.first_name + ' ' + comment.user.last_name, comment.user %></li>
          <% end %>
        </ul>
      <% else %>
        No comments
      <% end %>
    </article>
  <% end %>
</section>

app/views/reports/index.html.erb
<h1>Reports</h1>

<ul>
  <li><%= link_to "Top Users with more posts", top_user_posts_reports_path %></li>
  <li><%= link_to "Top Users with more likes", top_user_likes_reports_path %></li>
  <li><%= link_to "Top Posts with more likes", top_posts_reports_path %></li>
</ul>

app/views/reports/top_posts.html.erb
<ul>
  <% @posts.each do |post| %>
    <li><%= post.description %> by <%= post.user.first_name %> - Likes: <%= post.likes.count %></li>
  <% end %>
</ul>

app/views/reports/top_user_likes.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %> - Total likes: <%= user.posts.joins(:likes).count('likes.id') %></li>
  <% end %>
</ul>

app/views/reports/top_user_posts.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %> - Total posts: <%= user.posts.count %></li>
  <% end %>
</ul>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Lists of users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.first_name + ' ' + user.last_name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p>
  Name:
  <%= fullname(@user_decorator) %>
</p>

<p>
  Email:
  <%= @user_decorator.define_email %>
</p>

<p>
  Birthday:
  <%= @user_decorator.birthday_format %>
</p>

<p>
  Followers:
  <%= users_list(@user_decorator.followers) %>
</p>

<p>
  Following:
  <%= users_list(@user_decorator.following) %>
</p>

<p>
  Posts
  <dl>
    <% @user_decorator.posts.each do |post| %>
      <dt>Description:</dt>
      <dd><%= post.description %></dd>
      <dt>Likes:</dt>
      <dd><%= post.likes.count%></dd>
    <% end %>
  </dl>
</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>